twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        rpCode:
            level1: '%env(int:RPCODE_LEVEL1)%'
            level2: '%env(int:RPCODE_LEVEL2)%'
            level3: '%env(int:RPCODE_LEVEL3)%'

when@test:
    twig:
        strict_variables: true
