twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        hbCode:
            level1: '%env(int:HBCODE_LEVEL1)%'
            level2: '%env(int:HBCODE_LEVEL2)%'
            level3: '%env(int:HBCODE_LEVEL3)%'

when@test:
    twig:
        strict_variables: true
