twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        rpCode:
            level1: '%env(RPCODE_LEVEL1)%'
            level21: '%env(RPCODE_LEVEL21)%'
            level22: '%env(RPCODE_LEVEL22)%'

when@test:
    twig:
        strict_variables: true
